---
- name: Retrofit pre-Yubikey rootfs images with correct SSH config
  hosts: all
  gather_facts: no
  become: yes
  vars:
    rootfs_dir: "{{ (playbook_dir + '../../../../rootfs') | realpath }}"
    rootfs_includes_dir: "{{ rootfs_dir + '/customization/includes.chroot' }}"

  pre_tasks:
    - include_tasks: tasks/set-facts.yml
  tasks:    
    - debug:
        var: rootfs_includes_dir
        
    - name: Copy root ssh keys
      synchronize:
        src: "{{ rootfs_includes_dir }}/etc/jaiabot/ssh/root_authorized_keys"
        dest: "/tmp/root_authorized_keys"
        rsync_path: "sudo {{ RO_CMD }} rsync"
        
    - name: Copy sshd config
      synchronize:
        src: "{{ rootfs_includes_dir }}/etc/ssh/sshd_config.d/jaia_sshd.conf"
        dest: "/tmp/jaia_sshd.conf"
        rsync_path: "sudo {{ RO_CMD }} rsync"

    - name: Move files into place
      shell: |
        {{ RO_ROOT_CMD }} mkdir -p /etc/jaiabot/ssh        
        {{ RO_ROOT_CMD }} mv /tmp/root_authorized_keys /etc/jaiabot/ssh/root_authorized_keys
        {{ RO_ROOT_CMD }} mv /tmp/jaia_sshd.conf /etc/ssh/sshd_config.d/jaia_sshd.conf
        {{ RO_ROOT_CMD }} chown root:root /etc/ssh/sshd_config.d/jaia_sshd.conf
        
    - include_tasks: tasks/set-jaiabot-ssh-perms.yml
        
    - name: Install yubikey-manager
      shell: |
        {{ RO_ROOT_CMD }} apt-get update && apt-get -y install yubikey-manager
